name: Code Push Trigger

on:
  push:
    branches:
      - main
      - sandbox
      - quality

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Run a 2-line script
      run: echo ${{ secrets.SEC1 }}
        
    - name: Run a 3-line script
      run: echo ${{ vars.VAR1 }}

  reuse:
    uses: banmcr/workflowrepo/.github/workflows/reusable-workflow.yml@main
    with:
      my_variable: ${{ vars.VAR1 }}
    secrets:
      my_secret: ${{ secrets.SEC1 }}
