name: Code Push Trigger

on:
  push:
    branches:
      - main
      - sandbox
      - quality

jobs:
  build:
    runs-on: ubuntu-latest
    environment: $BRANCH_NAME
    env:
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

  reuse:
    uses: banmcr/workflowrepo/.github/workflows/reusable-workflow.yml@main
    with:
      my_variable: ${{ vars.VAR1 }}
    secrets:
      my_secret: ${{ secrets.SEC1 }}
